import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Great_Vibes , Inter } from 'next/font/google'
import Header from '@/components/Header';

const vibes = Great_Vibes ({
  weight: '400',
  subsets:["latin"] 
})
export { vibes };

const inter = Inter({
  weight: '400',
  subsets:["latin"] 
})
export { inter };

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Figma Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-black text-white ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
